Repository Dev-FE-1/Toy_Project_3_BeginAgain, pull requests merged in 2024-09, with the labels that each got.

#14 [setting] 초기 세팅 및 이슈/PR 템플릿 업로드
  .github/ISSUE_TEMPLATE/bug-🐞.md
  .github/ISSUE_TEMPLATE/feature-✨.md
  .github/ISSUE_TEMPLATE/help-😭.md
  .github/pull_request_template.md
  index.html
  src/App.tsx
  src/api/.gitkeep
  src/assets/.gitkeep
  src/components/theLayout/Container.tsx
  src/components/theLayout/NavbarLayout.tsx
  src/components/theLayout/theHeader/Header.tsx
  src/components/theLayout/theNavigation/Navigation.tsx
  src/components/theLayout/theNavigation/NavigationItem.tsx
  src/main.tsx
  src/pages/AddPlaylist.tsx
  src/pages/Bookmark.tsx
  src/pages/Home.tsx
  src/pages/MyPlaylist.tsx
  src/pages/Profile.tsx
  src/stores/.gitkeep
  src/styles/GlobalStyles.tsx
  src/styles/Theme.tsx
Labels: setting

#17 [feature] 카테고리 컴포넌트 생성 #13
  src/assets/logo.png
  src/components/theCommon/Category.tsx
  src/components/theCommon/PlaylistDetail.tsx
  src/pages/Home.tsx
Labels: feature

#19 공통 컴포넌트 modal 추가 및 addPlaylist 제작중
  package-lock.json
  src/components/theCommon/Modal.tsx
  src/pages/AddPlaylist.tsx
Labels: feature

#20 [feature] 공통컴포넌트 개발 # 12
  src/components/theCommon/LongButton.tsx
  src/components/theCommon/ShortButton.tsx
  src/components/theEmptyInfo/EmptyInfo.tsx
  src/components/theLayout/theNavigation/Navigation.tsx
  src/components/theLayout/theNavigation/NavigationItem.tsx
  src/pages/MyPlaylist.tsx
  src/pages/Profile.tsx
  src/styles/Theme.tsx
Labels: feature, style

#21 [feature] 공통 컴포넌트 개발과 상세보기 페이지 연결 #18
  index.html
  package-lock.json
  src/App.tsx
  src/assets/favicon.ico
  src/assets/favicon.png
  src/components/theCommon/Category.tsx
  src/components/theLayout/theHeader/BackButtonHeader.tsx
  src/components/theLayout/theHeader/LogoHeader.tsx
  src/components/thePlaylist/Feed.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/PlaylistDetailPage.tsx
  src/styles/Theme.tsx
Labels: feature

#24 [BugFix] TheNavigation 파일 수정
  src/components/layouts/navigations/TheNavigation.tsx
Labels: bug

#28 [bugFix] header 렌더링 오류 수정, hooks 파일 수정, FB 설정 및 레이아웃 수정 #26
  src/components/layouts/Container.tsx
  src/components/layouts/headers/TheHeader.tsx
  src/components/layouts/navigations/TheNavigation.tsx
  src/components/playlist/Feed.tsx
  src/hooks/playlists.ts
  src/hooks/useCreateComment.ts
  src/hooks/useDeleteComment.ts
  src/hooks/useDeletePlaylist.ts
  src/hooks/useFetchComments.ts
  src/hooks/useFetchPlaylist.ts
  src/hooks/useFetchPlaylists.ts
  src/hooks/useUpdatePlaylist.ts
  src/main.tsx
  src/routes/pages/AddPlaylist.tsx
  src/routes/pages/Bookmark.tsx
  src/routes/pages/Home.tsx
  src/routes/pages/MyPlaylist.tsx
  src/routes/pages/PlaylistDetailPage.tsx
  src/routes/pages/Profile.tsx
  src/styles/GlobalStyles.tsx
Labels: bug, style, setting

#36 [Bugfix] 양쪽 수정 충돌 해결
  package-lock.json
  package.json
  src/components/playlist/Playlist.tsx
  src/routes/pages/AddPlaylist.tsx
Labels: bug

#37 [Feature] myPlaylist 첫 화면 ui 초안, 빈화면 문구 컴포넌트 기능 구현 #29
  src/components/playlist/SavedPlaylists.tsx
  src/routes/pages/MyPlaylist.tsx
Labels: feature, style

#38 [Feature] AddPalylist 토스트 기능 추가 및 필수요소 스타일 추가
  src/components/playlist/Playlist.tsx
  src/routes/pages/AddPlaylist.tsx
  src/routes/pages/Home.tsx
Labels: feature

#43 [Feature] MyPlaylist UI 수정, 모달 및 토스트 기능, 모달 기능에서 오버레이 버그 수정, z-index 수정 #42
  src/components/SplashScreen.module.css
  src/components/common/TheModal.tsx
  src/components/common/Toast.tsx
  src/components/layouts/Container.tsx
  src/components/layouts/headers/BackButtonHeader.tsx
  src/components/layouts/headers/LogoHeader.tsx
  src/components/layouts/headers/TheHeader.tsx
  src/components/layouts/navigations/TheNavigation.tsx
  src/components/playlist/SavedPlaylists.tsx
  src/routes/pages/MyPlaylist.tsx
  src/routes/pages/SavedPlaylists.tsx
Labels: feature, style

#47 [feature] 완료버튼 기능 및 글자수 제한 기능 추가 #41
  src/components/layouts/headers/TheHeader.tsx
  src/routes/pages/AddPlaylist.tsx
  src/stores/addPlaylist.ts
Labels: feature, style

#48 Feature/playlist collection 25
  src/components/playlist/Playlist.tsx
  src/hooks/useToggleBookmark.ts
  src/routes/pages/Bookmark.tsx
  src/stores/useBookmark.ts
Labels: feature

#50 [bug] navigation 경로 수정, + 버튼 색상 바뀌지 않도록 수정
  src/components/layouts/navigations/NavigationItem.tsx
  src/components/layouts/navigations/TheNavigation.tsx
Labels: bug

#51 [Feature] 플레이리스트 컴포넌트 수정 #46
  src/components/playlist/Playlist.tsx
  src/routes/index.tsx
Labels: feature

#53 hotfix: 서버 에러 수정, 오타 수정, playlist?.id로 옵셔널 체이닝(타입오류 해결하기 위해)
  src/components/playlist/Playlist.tsx
  src/components/playlist/savedPlaylists.tsx
  src/hooks/useDeletePlaylist.ts
  src/hooks/useFetchComments.ts
  src/hooks/useUpdatePlaylist.ts
  src/routes/pages/Bookmark.tsx
  src/routes/pages/MyPlaylist.tsx
  src/routes/pages/SavedPlaylists.tsx
Labels: hotfix

#63 [Setting] 파이어베이스 인증 관련 코드 리팩토링 #61
  src/api/firebaseApp.ts
  src/components/SplashScreen.tsx
  src/components/common/LongButton.tsx
  src/components/common/PlaylistDetail.tsx
  src/components/playlist/Playlist.tsx
  src/hooks/useDeletePlaylist.ts
  src/hooks/useToggleBookmark.ts
  src/hooks/useUpdatePlaylist.ts
  src/routes/pages/Bookmark.tsx
  src/routes/pages/MyPlaylist.tsx
  src/routes/pages/PlaylistDetail.tsx
  src/routes/pages/Profile.tsx
  src/routes/pages/SavedPlaylists.tsx
  src/routes/pages/SignIn.tsx
  src/routes/protected/RequiresAuth.tsx
Labels: setting

#67 [feature] 북마크 UI 구현
  src/components/playlist/Playlist.tsx
  src/hooks/useToggleBookmark.ts
  src/routes/pages/Bookmark.tsx
Labels: feature, style

#68 [style] globalStyles 파일 수정, 스타일 적용 import 수정, navigation 작동 방식 변경, SavedPlaylistDetail 파일 생성 및 라우트 연결
  src/assets/fonts/Pretendard-Black.woff
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-ExtraBold.woff
  src/assets/fonts/Pretendard-ExtraLight.woff
  src/assets/fonts/Pretendard-Light.woff
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/Pretendard-Thin.woff
  src/components/common/Category.tsx
  src/components/common/Input.tsx
  src/components/common/LongButton.tsx
  src/components/common/PlaylistDetail.tsx
  src/components/common/ShortButton.tsx
  src/components/common/TheModal.tsx
  src/components/common/Toast.tsx
  src/components/emptyInfo/EmptyInfo.tsx
  src/components/layouts/Container.tsx
  src/components/layouts/headers/TheHeader.tsx
  src/components/layouts/navigations/NavigationItem.tsx
  src/components/layouts/navigations/TheNavigation.tsx
  src/components/playlist/Playlist.tsx
  src/main.tsx
  src/routes/index.tsx
  src/routes/pages/AddPlaylist.tsx
  src/routes/pages/PlaylistDetail.tsx
  src/routes/pages/Profile.tsx
  src/routes/pages/Profile2.tsx
  src/routes/pages/SavedPlaylists.tsx
  src/routes/pages/SavedPlaylistsDetail.tsx
  src/styles/GlobalStyles.tsx
  src/styles/Theme.tsx
  src/styles/emotion.d.ts
  src/styles/font.d.ts
  src/styles/globalFonts.ts
Labels: style, setting

#70 [Style] 플레이리스트 상세보기 페이지 퍼블리싱 및 버그 수정
  src/api/VideoData.ts
  src/components/common/PlaylistDetail.tsx
  src/components/playlist/Playlist.tsx
  src/components/playlist/PlaylistDetails.tsx
  src/hooks/useCreateComment.ts
  src/hooks/useUpdatePlaylist.ts
  src/routes/pages/Bookmark.tsx
  src/routes/pages/Home.tsx
  src/routes/pages/PlaylistDetail.tsx
  src/stores/addPlaylist.ts
  src/stores/useBookmark.ts
Labels: bug, style

#74 [Style] 플레이리스트 상세보기와 코멘트 공통 컴포넌트 생성 #64
  src/components/common/PlaylistDetail.tsx
  src/components/playlist/Comment.tsx
  src/components/playlist/PlaylistDetails.tsx
  src/routes/pages/PlaylistDetail.tsx
Labels: style

#73 [Feature] 프로필페이지 코드 수정 및 추가페이지 스타일 변경 #69
  src/routes/pages/AddPlaylist.tsx
  src/routes/pages/Profile.tsx
Labels: feature, style

#78 [Style] 404 NotFound 페이지 퍼블리싱 및 라우트 연결
  src/assets/pageNotFound.png
  src/routes/index.tsx
  src/routes/pages/NotFound.tsx
  src/styles/Theme.tsx
Labels: style

#79 [Feature] comments 모달 생성 및 중간 커밋
  src/components/Comments/Comments.tsx
  src/components/Comments/CommentsModal.tsx
  src/components/playlist/Comment.tsx
  src/hooks/useCreateComment.ts
  src/routes/pages/NotFound.tsx
  src/routes/pages/PlaylistDetail.tsx
Labels: feature

#81 [feature] 파이어베이스(스토어)로 북마크 생성, UI 다시 구현
  src/components/playlist/Playlist.tsx
  src/hooks/useFetchBookmark.ts
  src/hooks/useFetchUserBookmark.ts
  src/hooks/useToggleBookmark.ts
  src/routes/pages/Bookmark.tsx
  src/stores/useBookmark.ts
Labels: bug, feature, style

#83 [feature]북마크 컴포넌트화
  src/components/bookmarks/BookmarkList.tsx
  src/components/bookmarks/BookmarkModal.tsx
  src/hooks/useFetchUserBookmark.ts
  src/hooks/useToggleBookmark.ts
  src/routes/pages/Bookmark.tsx
Labels: bug, feature

#84 [Feature] savedMyPlaylist 페이지 UI 수정 및 헤더, 네브바 수정
  src/components/common/PlaylistDetail.tsx
  src/components/layouts/headers/TheHeader.tsx
  src/components/layouts/navigations/NavigationItem.tsx
  src/components/layouts/navigations/TheNavigation.tsx
Labels: style

#86 [Feature] 카테고리 공통컴포넌트에 기능 추가
  src/components/common/Category.tsx
  src/components/playlist/Playlist.tsx
  src/hooks/useFetchPlaylist.ts
  src/hooks/useFetchPlaylists.ts
  src/routes/pages/AddPlaylist.tsx
  src/routes/pages/Home.tsx
  src/stores/addPlaylist.ts
Labels: feature

#87 [Feature] 플레이리스트 내부 개별 동영상 리스트 구현
  src/api/firebaseApp.ts
  src/components/common/PlaylistDetail.tsx
  src/components/layouts/headers/TheHeader.tsx
  src/components/layouts/navigations/TheNavigation.tsx
  src/hooks/useDeletePlaylist.ts
  src/routes/index.tsx
  src/routes/pages/EditPlaylist.tsx
Labels: feature, style

#91 [Feature] comments 중간점검 후 피드백 수정
  src/components/Comments/Comments.tsx
  src/components/Comments/CommentsModal.tsx
  src/components/common/Toast.tsx
  src/components/playlist/PlaylistDetail.tsx
  src/hooks/useFetchComments.ts
  src/routes/pages/PlaylistDetail.tsx
  src/routes/pages/SavedPlaylistsDetail.tsx
Labels: feature

#94 [feature]북마크 수정필요사항 수정완료
  package-lock.json
  package.json
  src/components/bookmarks/BookmarkItem.tsx
  src/components/bookmarks/BookmarkModal.tsx
  src/components/common/Toast.tsx
  src/components/playlist/Playlist.tsx
  src/hooks/useFetchBookmark.ts
  src/hooks/useFetchUserBookmark.ts
  src/hooks/useToggleBookmark.ts
  src/routes/index.tsx
  src/routes/pages/Bookmark.tsx
  src/routes/pages/BookmarkedPlaylist.tsx
Labels: bug, feature

#96 [Style] 카테고리 호버 삭제 및 추가페이지 스타일 변경 및 프로필페이지 스타일 변경 #92
  src/components/common/Category.tsx
  src/components/layouts/headers/TheHeader.tsx
  src/routes/pages/AddPlaylist.tsx
  src/routes/pages/Profile.tsx
Labels: style

#100 [Style] SignIn 페이지 수정 #90
  src/assets/googleLogo.png
  src/assets/splash.jpg
  src/components/common/LongButton.tsx
  src/routes/pages/SignIn.tsx
Labels: style

#103 [Feature] edit playlist 페이지 작업
  src/components/EditPlaylistModal.tsx
  src/components/layouts/Container.tsx
  src/components/layouts/headers/TheHeader.tsx
  src/components/playlist/PlaylistDetail.tsx
  src/routes/index.tsx
  src/routes/pages/DeleteVideos.tsx
  src/routes/pages/EditPlaylist.tsx
  src/routes/pages/EditPlaylistInfo.tsx
  src/routes/pages/SavedPlaylistsDetail.tsx
  src/styles/Theme.tsx
Labels: feature, style

#105 [feature] SortableJS를 활용해서 디테일페이지 DnD 구현
  src/components/common/Toast.tsx
  src/components/playlist/PlaylistDetail.tsx
  src/hooks/useFetchPlaylist.ts
  src/hooks/useFetchUser
  src/routes/pages/Bookmark.tsx
Labels: feature

#106 [Feature] 공개 설정 기능 구현 #97
  src/components/playlist/PlaylistDetail.tsx
  src/hooks/useFetchPlaylists.ts
  src/routes/pages/Home.tsx
  src/routes/pages/MyPlaylist.tsx
  src/stores/addPlaylist.ts
Labels: feature

#107 [Style] 전체 레이아웃 조정 및 스크롤 기능 추가
  src/components/EditPlaylistModal.tsx
  src/components/layouts/Container.tsx
  src/components/layouts/headers/TheHeader.tsx
  src/components/playlist/PlaylistDetail.tsx
  src/routes/pages/AddPlaylist.tsx
  src/routes/pages/Bookmark.tsx
  src/routes/pages/DeleteVideos.tsx
  src/routes/pages/EditPlaylistInfo.tsx
  src/routes/pages/Home.tsx
  src/routes/pages/MyPlaylist.tsx
  src/routes/pages/PlaylistDetail.tsx
  src/routes/pages/Profile.tsx
  src/styles/GlobalStyles.tsx
  src/styles/Theme.tsx
Labels: style

#109 [bug] DnD 콘솔에러 및 파이어스토어 데이터베이스 저장안됨 오류 수정
  src/components/playlist/PlaylistDetail.tsx
  src/hooks/useFetchPlaylists.ts
Labels: bug, feature

#112 [Feature] 파이어베이스 Users 컬렉션 생성 #101
  src/api/firebaseAuth.ts
  src/components/bookmarks/BookmarkItem.tsx
  src/components/bookmarks/BookmarkModal.tsx
  src/components/common/Toast.tsx
  src/components/playlist/Playlist.tsx
  src/hooks/useFetchComments.ts
  src/hooks/useFetchUser.ts
  src/routes/pages/Home.tsx
  src/routes/pages/SignIn.tsx
Labels: feature

#111 [Style] 헤더 이름 및 버튼 수정, 편집 모달 위치 수정
  src/components/EditPlaylistModal.tsx
  src/components/layouts/headers/TheHeader.tsx
  src/components/layouts/navigations/TheNavigation.tsx
  src/components/playlist/PlaylistDetail.tsx
  src/routes/pages/AddPlaylist.tsx
  src/routes/pages/Bookmark.tsx
  src/routes/pages/DeleteVideos.tsx
  src/routes/pages/EditPlaylistInfo.tsx
  src/routes/pages/MyPlaylist.tsx
  src/routes/pages/Profile.tsx
  src/styles/Theme.tsx
Labels: style

#116 [Feature] Playlist.tsx에 업로드한 유저데이터 불러오기
  src/api/firebaseAuth.ts
  src/assets/signIn.jpg
  src/components/playlist/Playlist.tsx
  src/hooks/useFetchUser.ts
  src/routes/pages/SignIn.tsx
Labels: feature

#121 [Bug] videoId 불러오기 버그 수정 및 playlist.tsx 코드 리팩토링
  src/api/VideoData.ts
  src/components/playlist/Playlist.tsx
  src/components/playlist/PlaylistDetail.tsx
  src/hooks/useExtractVideoId.ts
  src/hooks/useFetchPlaylistData.ts
  src/hooks/useHeartData.ts
  src/routes/pages/AddPlaylist.tsx
Labels: bug

#126 [Bug] 비공개 설정시 삭제안되는 문제 해결 및 DB 통합 #125
  src/components/playlist/PlaylistDetail.tsx
  src/hooks/useFetchPlaylists.ts
  src/routes/pages/AddPlaylist.tsx
  src/routes/pages/Home.tsx
  src/stores/addPlaylist.ts
Labels: bug

#128 [bug] 북마크페이지 토스트 버그 개선 (추가로 북마크 PlayList -> Playlist 변경 )
  src/components/bookmarks/BookmarkItem.tsx
  src/components/common/Toast.tsx
  src/hooks/useItemReorder.ts
  src/routes/pages/Bookmark.tsx
  src/stores/useBookmark.ts
Labels: bug

#129 [Feature] comments modal UI 수정 #102
  src/components/Comments/Comments.tsx
  src/components/Comments/CommentsModal.tsx
  src/components/playlist/PlaylistDetail.tsx
  src/hooks/usePlaylistData.ts
  src/hooks/useSortablePlaylist.ts
  src/hooks/useToggleDescription.ts
  src/hooks/useVideoTitles.ts
Labels: feature, style

#132 [Feature] EditplaylistInfo 정보 수정 페이지 기능 구현
  src/components/layouts/headers/TheHeader.tsx
  src/components/playlist/EditPlaylistModal.tsx
  src/components/playlist/PlaylistDetail.tsx
  src/hooks/useEditPlaylistInfo.ts
  src/routes/index.tsx
  src/routes/pages/EditPlaylistInfo.tsx
  src/stores/header.ts
Labels: feature

#136 [Feature] 파이어베이스 Likes 데이터 저장하고 해제하기 #118
  src/api/likes.ts
  src/components/playlist/Playlist.tsx
  src/hooks/useDeletePlaylist.ts
  src/hooks/useLikeData.ts
Labels: feature

#139 [bug]내플리 북마크설정 재발 개선 완
  src/components/bookmarks/BookmarkItem.tsx
  src/components/playlist/Playlist.tsx
  src/hooks/useFetchPlaylistData.ts
Labels: bug

#140 [Feature] 파이어베이스 DB 좋아요 연결 #118
  src/components/playlist/Playlist.tsx
  src/hooks/useLikeData.ts
Labels: feature

#142 [Feature] 홈페이지 데이터 최신순 불러오기와 댓글 숫자데이터 연결 #141
  src/components/common/SplashScreen.tsx
  src/components/playlist/Playlist.tsx
  src/hooks/useFetchComments.ts
  src/routes/pages/Home.tsx
  src/routes/pages/SignIn.tsx
  src/stores/header.ts
Labels: feature

#143 [Style] 케밥케이스 추가, 모달 수정, 편집페이지 경로 수정, 기타 스타일 수정
  src/components/playlist/EditPlaylistModal.tsx
  src/components/playlist/PlaylistDetail.tsx
Labels: style

#150 [ Feature] 프로필 편집페이지 사진 변경 추가 (진행중) #89
  src/hooks/usePlaylistData.ts
  src/routes/pages/EditProfile.tsx
  src/routes/pages/Home.tsx
  src/stores/editProfile.ts
Labels: feature

#151 [Style] comments modal UI 변경 #145
  src/components/Comments/Comments.tsx
  src/components/Comments/CommentsModal.tsx
  src/components/playlist/EditPlaylistModal.tsx
  src/components/playlist/PlaylistDetail.tsx
Labels: style

#153 [bug]북마크썸네일 버그 및 북마크,드래그 위치 수정
  src/components/bookmarks/BookmarkItem.tsx
  src/hooks/useFetchBookmark.ts
Labels: bug, feature

#154 [Feature] 비디오 삭제 기능 구현 및 디테일 페이지 스타일 수정
  src/components/playlist/EditPlaylistModal.tsx
  src/components/playlist/PlaylistDetail.tsx
  src/hooks/useDeleteVideo.ts
  src/routes/pages/SavedPlaylists.tsx
Labels: feature, style

#158 [bug]마이플리 토스트 개선
  src/components/bookmarks/BookmarkItem.tsx
  src/routes/pages/Bookmark.tsx
  src/routes/pages/MyPlaylist.tsx
  src/routes/pages/SavedPlaylists.tsx
Labels: bug

#157 [Feature] 프로필 수정페이지 기능 개발 #89
  src/components/common/TheModal.tsx
  src/components/layouts/headers/TheHeader.tsx
  src/routes/pages/EditProfile.tsx
  src/stores/editProfile.ts
Labels: feature

#160 [Feature] 무한스크롤 구현 #148
  src/api/playlistApi.tsx
  src/components/infiniteScroll/InfiniteScroll.tsx
  src/hooks/useInfiniteScroll.ts
  src/routes/pages/Home.tsx
Labels: feature

#164 [Bug] infinite scroll 긴급 수정 #163
  src/hooks/useInfiniteScroll.ts
Labels: bug, hotfix

#165 [Bug] 무한스크롤 비공개 필터 설정 #163
  src/api/playlistApi.tsx
  src/components/infiniteScroll/InfiniteScroll.tsx
  src/hooks/useInfiniteScroll.ts
  src/routes/pages/Home.tsx
Labels: bug, hotfix

#166 [Feature] 추가페이지 툴팁 추가 및 글자간격 늘림 #161
  package-lock.json
  package.json
  src/routes/pages/AddPlaylist.tsx
Labels: feature, style

#168 [Bug] 댓글 삭제 버그 수정 #152
  package-lock.json
  package.json
  src/components/Comments/CommentsModal.tsx
  src/hooks/useCreateComment.ts
Labels: bug

#171 [feature] 북마크시점으로 북마크페이지 정렬 (드래그기능은 아직)
  src/components/bookmarks/BookmarkModal.tsx
  src/hooks/useFetchBookmark.ts
  src/hooks/useFetchUserBookmark.ts
  src/routes/pages/Bookmark.tsx
Labels: feature

#173 [feature]북마크디테일페이지 케밥,햄버거아이콘 안보이게 하기
  package-lock.json
  src/components/playlist/PlaylistDetail.tsx
Labels: bug, feature

#175 [Style] 추가페이지 헤더 한글명으로 변경 #174
  src/routes/pages/AddPlaylist.tsx
Labels: style

#178 [Feature] 프로필 사진 크기 조정, 추가페이지 완료 후 마이플리로 이동 및 토스트 띄움, 자잘한 에러 수정 #176
  src/components/layouts/headers/TheHeader.tsx
  src/components/playlist/Playlist.tsx
  src/routes/pages/EditProfile.tsx
  src/routes/pages/Home.tsx
  src/routes/pages/MyPlaylist.tsx
  src/routes/pages/Profile.tsx
Labels: feature, style

#179 [feature] 디테일 페이지 프로필 사진과 유저이름 구현, 댓글과 동영상 삭제 바텀시트에 motion 효과 구현 및 수정
  src/components/Comments/CommentsModal.tsx
  src/components/playlist/EditPlaylistModal.tsx
  src/components/playlist/PlaylistDetail.tsx
  src/hooks/useFetchUserId.ts
Labels: feature, style

#182 [feature]북마크 드래그 미완성,ORDER필드추가
  src/hooks/useDragAndDrop.ts
  src/hooks/useFetchBookmark.ts
  src/hooks/useFetchUserBookmark.ts
  src/hooks/useToggleBookmark.ts
  src/routes/pages/Bookmark.tsx
Labels: feature

#183 [Feature] test 코드 생성 및 페이지 스타일링 수정
  .github/workflows/playwright.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  src/components/Comments/CommentsModal.tsx
  src/components/layouts/Container.tsx
  src/components/layouts/headers/TheHeader.tsx
  src/components/playlist/EditPlaylistModal.tsx
  src/components/playlist/Playlist.tsx
  src/components/playlist/PlaylistDetail.tsx
  src/routes/pages/AddPlaylist.tsx
  src/routes/pages/EditPlaylistInfo.tsx
  src/routes/pages/NotFound.tsx
  src/routes/pages/SignIn.tsx
  tests-examples/demo-todo-app.spec.ts
  tests/example.spec.ts
  tests/tests/signIn.spec.ts
Labels: style, test

#184 [Style] readme작성 #169
  README.md
Labels: style

#195 [Refactoring] 리팩토링 코드리뷰 수정 #194
  .gitignore
  src/api/firebaseAuth.ts
  src/api/playlistApi.tsx
  src/components/Comments/Comments.tsx
  src/hooks/useCreateComment.ts
  src/hooks/useExtractVideoId.ts
  src/hooks/useInfiniteScroll.ts
Labels: refactoring
